# Generated by Django 3.2 on 2021-05-14 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_cargotypes_subscription_subscriptiontypes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ip',
            options={'verbose_name': 'Ip адрес', 'verbose_name_plural': 'Ip адреса'},
        ),
        migrations.AlterModelOptions(
            name='portuser',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'Подписку', 'verbose_name_plural': 'Подписки'},
        ),
        migrations.AddField(
            model_name='ip',
            name='quantity_user',
            field=models.IntegerField(default=1, verbose_name='Колличество пользователей'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ip',
            name='ip',
            field=models.GenericIPAddressField(verbose_name='Ip адрес'),
        ),
        migrations.AlterField(
            model_name='ip',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='portuser',
            name='billing_address',
            field=models.CharField(max_length=200, verbose_name='Платежный адрес'),
        ),
        migrations.AlterField(
            model_name='portuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='portuser',
            name='full_name',
            field=models.CharField(max_length=200, verbose_name='Полное имя'),
        ),
        migrations.AlterField(
            model_name='portuser',
            name='user_ip',
            field=models.ManyToManyField(blank=True, to='account.Ip', verbose_name='Ip адрес пользователя'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='cargo',
            field=models.ManyToManyField(blank=True, to='account.CargoTypes', verbose_name='Груз'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='date_from',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата начала подписки'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='date_to',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания подписки'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.subscriptiontypes', verbose_name='Тип подписки'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
