# Generated by Django 3.2 on 2021-05-14 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210514_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='portuser',
            name='quantity_ip',
            field=models.IntegerField(default=1, verbose_name='Колличество ip адресов'),
            preserve_default=False,
        ),
    ]
