# Generated by Django 3.2 on 2021-07-01 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_portuser_quantity_ip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='subscription',
            new_name='subscription_types',
        ),
        migrations.RemoveField(
            model_name='cargotypes',
            name='name_cargo',
        ),
        migrations.AddField(
            model_name='cargotypes',
            name='name',
            field=models.CharField(default='nill', max_length=100, verbose_name='Название груза'),
            preserve_default=False,
        ),
    ]
