# Generated by Django 3.2 on 2021-05-15 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='body',
            options={'verbose_name': 'Текст', 'verbose_name_plural': 'Текст'},
        ),
        migrations.AlterModelOptions(
            name='list',
            options={'verbose_name': 'Список', 'verbose_name_plural': 'Список'},
        ),
        migrations.AlterModelOptions(
            name='pages',
            options={'verbose_name': 'Страница', 'verbose_name_plural': 'Страницы'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name': 'Раздел', 'verbose_name_plural': 'Разделы'},
        ),
        migrations.AddField(
            model_name='pages',
            name='url',
            field=models.URLField(default='url-url', help_text='Пример формата "Privacy-policy"', verbose_name='URL страницы'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='body',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='body', to='pages.section'),
        ),
        migrations.AlterField(
            model_name='list',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list', to='pages.section'),
        ),
        migrations.AlterField(
            model_name='pages',
            name='page_name',
            field=models.CharField(max_length=100, verbose_name='Название страницы'),
        ),
        migrations.AlterField(
            model_name='section',
            name='pages',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section', to='pages.pages'),
        ),
    ]
