# Generated by Django 3.2 on 2021-05-15 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20210515_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='main_title',
            field=models.CharField(blank=True, help_text='Необязательное поле', max_length=200, null=True, verbose_name='Главный заголовок'),
        ),
    ]
