# Generated by Django 3.2 on 2021-05-16 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_pages_main_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=50, verbose_name='Номер для связи')),
                ('whats_app', models.CharField(max_length=50, verbose_name='Номер WhatsApp')),
                ('telegram', models.CharField(max_length=50, verbose_name='Telegram')),
                ('email', models.CharField(max_length=50, verbose_name='Email адрес')),
            ],
        ),
    ]
