# Generated by Django 3.2 on 2021-07-01 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Контакты', 'verbose_name_plural': 'Контакты'},
        ),
    ]
